from nginx
ADD node-v8.9.1-linux-x64.tar.xz /usr/local
RUN  ln -s  /usr/local/node-v8.9.1-linux-x64 /usr/local/node &&   ln -s /usr/local/node/bin/node /usr/local/bin/node && ln -s /usr/local/node/bin/npm /usr/local/bin/npm 
expose 80
